apiVersion: v2
name: vcluster
description: A Helm chart for Kubernetes with vcluster, Traefik, and custom IngressRouteTCP

type: application
version: 0.1.0
appVersion: "1.16.0"


dependencies:
  - name: vcluster
    version: "0.19.5"
    repository: "https://charts.loft.sh"
  # - name: traefik
  #   version: "10.3.2"
  #   repository: "https://helm.traefik.io/traefik"